runtime: aspnetcore
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  CONNECTIONSTRINGS__DEFAULTCONNECTION: "server=35.192.233.78;database=test;user=<USER>;password=<PASSWORD>;CertificateFile=client.pfx;SSL Mode=Required"
