runtime: aspnetcore
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.0
  disk_size_gb: 10

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

env_variables:
  CONNECTIONSTRINGS__DEFAULTCONNECTION: "Host=35.222.49.3;Database=test;Username=test;Password=test123456;SslMode=Require;TrustServerCertificate=true"
  Email__SendGridKey: "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"
  GoogleCloudStorage__BucketName: "test-dpa"
  GoogleCloudStorage__APICredentialLocation: "./test-cloud-storage.json"
  GoogleCloudStorage__ProjectId: "dpa-waiver"
  CloudSQL__CertificateFile: "./client.pfx"
  
  